concert: enable nesting await imports
ufo-kit/concert pull request #494
Opened 2022-05-20 15:43 UTC by tfarago

Improvement of #482 which allows to nest module imports which need to run async code in a loop.

@MarcusZuber go ahead and break it again ;-)

Some scenarios are known not to work but I think they are easily avoidable and we throw a pretty instructive `ImportError` in case these occur.

This won't work:
```python
# the `await' needs to run the import in a loop 
# and on the next line we try to run the loop as well, so, nesting
await asyncio.sleep(0)
loop.run_until_complete(asyncio.sleep(0))
```

And this won't work:
```python
# barmodule:
await asyncio.sleep(0)

# foomodule:
async def foo():
    import barmodule

# We need to be imported in a loop and try to import
# module which will need to run a loop, nesting again.
await foo()
```

2022-05-20 15:46 UTC, tfarago commented
I havent' checked it super-thoroughly, so even if you don't manage to break it let me merge it a bit later next week. I also need to add some tests.

2022-05-20 15:47 UTC, tfarago commented on bin/concert
> +def is_import(node):
move this into _eval_nodes, nothing here is supposed to be accessed from outside.

2022-05-23 07:49 UTC, MarcusZuber requested changes
I was not able to break it for the 'standard' cases.

It even looks quite elegant :smiley: .

The only thing I recognized was, that awaitables, that are not awaited are not created and executed.

E.g. `b = LinearMotor()` or this:

```python
from concert.coroutines.base import start
async def a():
    print("Hallo")
    return 0.

b = start(a())
```

If you put this in a module, you can even do `from module import b`, but b then is not defined in the session afterwards.

2022-05-23 13:31 UTC, MarcusZuber commented
I remebered what was  different in the morning (and you will not like it). In the morning I tested it on my private pc with python3.10...

With this session:
```python
"""# *session* session manual

## Usage

## Notes
"""

import logging
from inspect import iscoroutinefunction
import concert
concert.require("0.32.0")

from concert.quantities import q
from concert.session.utils import ddoc, dstate, pdoc, code_of
import numpy as np

LOG = logging.getLogger(__name__)


from concert.coroutines.base import start
async def a():
    print("Hallo")
    return 0.

b = start(a())
```

I get this output
```python
(venv) marcus@marcus-desktop:~/.PycharmProjects/concert$ concert start test 
Welcome to Concert 0.32.0dev
# *session* session manual

## Usage

## Notes

test > b
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 b

NameError: name 'b' is not defined

test > 

```

2022-05-23 14:19 UTC, MarcusZuber commented
> What's your IPython and prompt_toolkit version? For me with python 3.10.4, IPython 8.3.0 and prompt_toolkit 3.0.29 all is fine... I get the warning but that I can quickly fix.

Same versions for me. That's confusing... If you like, I can send you my full virtual-environment.

2022-05-23 15:18 UTC, MarcusZuber commented
Ok, now it works fine. That was a stupid one...

2022-05-23 15:27 UTC, MarcusZuber commented on bin/concert
> +            path = [os.getcwd(), SESSION_PATH] + sys.path
Otherwise I execute accidentally stuff from my home folder.

2022-05-23 15:31 UTC, tfarago commented on bin/concert
> +            path = [os.getcwd(), SESSION_PATH] + sys.path
Sure, why not

2022-05-25 07:21 UTC, merged