Enhancement: add endpoint registration to base camera
ufo-kit/concert pull request #541
Opened 2024-08-09 15:22 UTC by sarkarchandan

**Premise**: To make a concert session with multiple utilities such as remote writing, online reconstruction, qa etc. we need to enable the base camera class to accommodate multiple endpoints like the UCA network camera. In the proposed change we enable the base camera class to maintain a group of senders internally instead of one.

Following concert session is used to test the functionality.

```python
import asyncio
import logging
import os
from inspect import iscoroutinefunction
import numpy as np
import zmq
import concert
from concert.experiments.addons import tango as tango_addons
from concert.quantities import q
from concert.devices.motors.dummy import LinearMotor, ContinuousRotationMotor
from concert.devices.shutters.dummy import Shutter
from concert.storage import RemoteDirectoryWalker
from concert.ext.viewers import PyQtGraphViewer
from concert.networking.base import get_tango_device
from concert.experiments.synchrotron import RemoteRadiography
from concert.devices.cameras.dummy import FileCamera
from concert.helpers import CommData

# Run Acquisitions Walker Writer: concert tango walker --loglevel perfdebug --port 7001
# Run Reconstruction: concert tango reco --loglevel perfdebug --port 7002
# Run Reconstruction Walker Writer: concert tango walker --loglevel perfdebug --port 7003

# Camera
pattern = "/home/ws/nj4412/workspace/projects/analytical_methods/data/measurements/tiff5x/image_seq/*.tif"
camera = await FileCamera(pattern=pattern)
if await camera.get_state() == 'recording':
    await camera.stop_recording()

await camera.set_roi_width(2016 * q.px)
await camera.set_roi_height(2016 * q.px)
await camera.set_frame_rate(20 / q.s)
#await camera.set_fill_data(True)

SERVERS = {
        "walker": CommData("localhost", port=8997, socket_type=zmq.PUSH),
        "reco": CommData("localhost", port=8993, socket_type=zmq.PUSH),
        "live": CommData("localhost", port=8995, socket_type=zmq.PUB, sndhwm=1)
}

for comm in SERVERS.values():
    try:
        await camera.register_endpoint(comm)
    except Exception as e:
        print(f"re-registering `{comm.server_endpoint}'")
        await camera.unregister_endpoint(comm)
        await camera.register_endpoint(comm)

# Walker
root = "/home/ws/nj4412/workspace/projects/testbed/concert_dev_tests/root"
walker_dev_uri = f"{os.uname()[1]}:7001/concert/tango/walker#dbase=no"
walker_device = get_tango_device(walker_dev_uri)
await walker_device.write_attribute('endpoint', SERVERS["walker"].client_endpoint)
walker_device.set_timeout_millis(300000)
walker = await RemoteDirectoryWalker(device=walker_device, root=root, bytes_per_file=2**40)

# Experiment
shutter = await Shutter()
flat_motor = await LinearMotor()
tomo = await ContinuousRotationMotor()
exp = await RemoteRadiography(walker=walker, camera=camera, shutter=shutter, flat_motor=flat_motor,
                              radio_position=0*q.mm, flat_position=10*q.mm, 
                              num_darks=100, num_flats=200, num_projections=3000)
exp.add_device_to_log("MockFileCamera", camera)
exp.add_device_to_log("MockShutter", shutter)
exp.add_device_to_log("MockMotor", flat_motor)

# Writer
writer = await tango_addons.ImageWriter(exp, exp.acquisitions)

# Live View
viewer = await PyQtGraphViewer(show_refresh_rate=True)
viewer.subscribe(SERVERS["live"].client_endpoint)

# Reconstruction
remote_reco_walker_dev_uri = f"{os.uname()[1]}:7003/concert/tango/walker#dbase=no"
remote_reco_walker_device = get_tango_device(remote_reco_walker_dev_uri)
remote_reco_walker_device.set_timeout_millis(600000)
remote_reco_walker = await RemoteDirectoryWalker(device=remote_reco_walker_device, root=root,
                                           bytes_per_file=2**40)

reco_dev_uri = f"{os.uname()[1]}:7002/concert/tango/reco#dbase=no"
reco_device = get_tango_device(reco_dev_uri)
await reco_device.write_attribute('endpoint', SERVERS["reco"].client_endpoint)
reco_device.set_timeout_millis(500000)
await reco_device.setup_walker(
    [remote_reco_walker_dev_uri, root, "tcp", "localhost", "8996"]
)
reco = await tango_addons.OnlineReconstruction(reco_device, exp, do_normalization=True,
                                               average_normalization=True,
                                               slice_directory="online-slices")
await reco.set_region([-700., 700., 1.])
await reco.set_center_position_x([1012.8] * q.px)
await reco.set_fix_nan_and_inf(True)
await reco_device.write_attribute('center_position_z',
                                  [(await camera.get_roi_height()).magnitude / 2 + 0.5])
await reco_device.write_attribute('number', 3000)
await reco_device.write_attribute('overall_angle', np.pi)
_ = reco.reconstruct()
```
**NOTE**: The aspect of Tango device timeout is still a pressing matter, at least from the context running local sessions with real data. In this example we have used large values to set the device timeouts to make sure, that we can work with realistic scenarios.

2024-08-09 15:25 UTC, sarkarchandan commented
@MarcusZuber, I am not completely sound about the implications of this change on derived camera types, which extend from base camera. Please let me know, if and what additional changes should be done for them.

2024-08-15 10:04 UTC, MarcusZuber approved these changes
I like it.
The only thing (but this is more general than this PR) would be to also add something like "unregister_all_endpoints", but this would also require uca-net to be updated. (At the beamlines we do complicated detach/atatch of consumers and keeping track of the right endpoints, especially when used from multiple concert sessions, can get a bit messy.)

2024-08-15 10:05 UTC, MarcusZuber commented
I like, that the interface for "local endpoints" and the uca-net implementation is now identical.

2024-08-15 10:08 UTC, MarcusZuber commented
> I like, that the interface for "local endpoints" and the uca-net implementation is now identical.

Wait, it is not the same. I would suggest to change the uca.camera implementation accordingly (to provide a ComData object instead of the string and the function extracts the string from it).

2024-08-16 12:42 UTC, sarkarchandan commented
> My suggestion would be to also change concert.devices.cameras.uca.RemoteCamera.register_enpoint that a ComData object is passed to the function.

Done.

2024-08-22 07:36 UTC, tfarago requested changes
I fixed and polished some things in my commits marked to be squashed. The creation of the tasks with the lambda functions was complicated to my taste and not necessary. Once we have some rudimentary tests and docs we can merge.

2024-08-22 07:36 UTC, tfarago commented on concert/devices/cameras/base.py
> +    async def unregister_endpoint(self, endpoint: CommData) -> None:
Needs docstring + test.

2024-08-22 07:36 UTC, tfarago commented on concert/devices/cameras/base.py
> +    async def register_endpoint(self, endpoint: CommData) -> None:
Needs docstring + test.

2024-08-22 07:36 UTC, tfarago commented on concert/helpers.py
> +    def __hash__(self) -> int:
all three `__eq__`, `__ne__`, `__hash__` need to be tested.

2024-08-22 12:25 UTC, tfarago commented
@MarcusZuber please take a final look, then I will merge.

2024-08-23 06:45 UTC, MarcusZuber approved these changes

2024-08-23 13:34 UTC, merged